name: build
on:
  push:
    branches: [ master ]
  pull-request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - id: pull
        name: Pull repository
        uses: actions/checkout@v2
      - id: configure
        name: Configure project
        run: |
          mkdir build
          cd build
          cmake -G "Ninja Multi-Config" ..
      - id: build
        name: Build project
        run: |
          cd build
          cmake --build . --config Release
